# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aabfd2a20846430136e081610a30f630b98dc651c18679792162e98e16e69ccc5f60393b6a76f0c690607d5fd84afdc65ed79e20e4b17630f5457a9d238f2106

test:
  secret_key_base: 070376190da1464417fe81f90bf92abf4c6bb09fd8348ab852d87ecb5975a10b33a06282f0e744c0bd7db4f0b5c114ad1fbb3e4890f0a7db115e0b4991dbb980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
